#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Preparing to push changes..."
echo "As part of the pre-push process, all tests will be executed."

npm run test
cd frontend
npm run lint:format
cd ..
cd backend
npm run lint:format

if [ $? -ne 0 ]; then
  echo "One or more tests failed! Push aborted."
  exit 1
fi

echo "All tests passed successfully! Proceeding with the push."